import type {
  ActivityNote,
  Company,
  Contact,
  CustomerPortfolio,
  Deal,
  Goal,
  Invoice,
  Lead,
  Project,
} from "./types";

/** Per-row demo values for portfolio columns that were previously empty (KYC, Lursoft, etc.). Index = nr − 1. */
const DEMO_CUSTOMER_KYC: Partial<CustomerPortfolio>[] = [
  {
    lursoft: "Verified · financial statements retrieved",
    industry: "Advertising & market research",
    naceCode: "73.11",
    kycForm: "Received 18.01.2023",
    idCopy: "ID copy + specimen signature",
    meetingDate: "25.01.2023",
    clientAcceptanceComplete: "Committee 27.01.2023",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "02.02.2023",
    additionalInvoicing: "None",
    contactEmail: "janis.banis@allin.lv",
    whatsapp: "+371 2911 2204",
    lastContactDate: "08.05.2026",
  },
  {
    lursoft: "Profile active · no alerts",
    industry: "Administrative services",
    naceCode: "82.11",
    kycForm: "Received 03.02.2023",
    idCopy: "Passport certified copy",
    meetingDate: "10.02.2023",
    clientAcceptanceComplete: "Approved 12.02.2023",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "15.02.2023",
    additionalInvoicing: "None",
    contactEmail: "ilze.milze@xxx-sia.lv",
    whatsapp: "+371 2634 8810",
    lastContactDate: "06.05.2026",
  },
  {
    lursoft: "Annual refresh · Q2 2025",
    industry: "Freight transport & logistics",
    naceCode: "49.41",
    kycForm: "Digital pack 02.05.2025",
    idCopy: "UB extract + directors ID",
    meetingDate: "21.05.2025",
    clientAcceptanceComplete: "Partner sign-off 23.05.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "28.05.2025",
    additionalInvoicing: "Travel at cost + cap",
    contactEmail: "kristaps.plume@greenlane.lv",
    whatsapp: "+371 2205 4412",
    lastContactDate: "11.05.2026",
  },
  {
    lursoft: "PSD profile verified",
    industry: "Payment institutions / EMI support",
    naceCode: "64.19",
    kycForm: "Enhanced DD complete",
    idCopy: "UB + ownership chart certified",
    meetingDate: "14.07.2025",
    clientAcceptanceComplete: "Risk committee 18.07.2025",
    riskLevel: "Elevated (regulated)",
    contractSigned: "Yes",
    contractDate: "24.07.2025",
    additionalInvoicing: "Change orders quoted",
    contactEmail: "annika.vitola@wavepayments.eu",
    whatsapp: "+371 2888 9031",
    lastContactDate: "13.05.2026",
  },
  {
    lursoft: "Branch filing confirmed",
    industry: "Research & development services",
    naceCode: "72.19",
    kycForm: "Pack received 28.03.2025",
    idCopy: "Parent registry attestation",
    meetingDate: "05.04.2025",
    clientAcceptanceComplete: "Approved 08.04.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "11.04.2025",
    additionalInvoicing: "None",
    contactEmail: "pauls.eglitis@rigatechcampus.lv",
    whatsapp: "+371 2944 5518",
    lastContactDate: "09.05.2026",
  },
  {
    lursoft: "Group file linked · LV record",
    industry: "Retail trade",
    naceCode: "47.91",
    kycForm: "Received 22.04.2025",
    idCopy: "ID copies (2 signatories)",
    meetingDate: "30.04.2025",
    clientAcceptanceComplete: "Email confirmation 02.05.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "06.05.2025",
    additionalInvoicing: "None",
    contactEmail: "sofia.marin@heliosretail.ee",
    whatsapp: "+372 5341 9022",
    lastContactDate: "05.05.2026",
  },
  {
    lursoft: "Verified · transport licence on file",
    industry: "Cargo handling & warehousing",
    naceCode: "52.24",
    kycForm: "Received 05.03.2025",
    idCopy: "ID + specimen signature",
    meetingDate: "12.03.2025",
    clientAcceptanceComplete: "Approved 14.03.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "19.03.2025",
    additionalInvoicing: "Site visits extra",
    contactEmail: "marta.liepa@balticfreight.lt",
    whatsapp: "+370 612 33441",
    lastContactDate: "04.05.2026",
  },
  {
    lursoft: "Foreign branch checks OK",
    industry: "Computer programming / SaaS",
    naceCode: "62.01",
    kycForm: "KYB questionnaire + charter",
    idCopy: "Passport (founder)",
    meetingDate: "01.07.2025",
    clientAcceptanceComplete: "Approved 04.07.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "10.07.2025",
    additionalInvoicing: "None",
    contactEmail: "jonas.berg@nordicsaas.io",
    whatsapp: "+46 70 441 2291",
    lastContactDate: "02.05.2026",
  },
  {
    lursoft: "LV branch registry synced",
    industry: "Manufacture of fabricated metal",
    naceCode: "25.11",
    kycForm: "Received 08.09.2025",
    idCopy: "ID copy + PoA",
    meetingDate: "18.09.2025",
    clientAcceptanceComplete: "Approved 20.09.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "25.09.2025",
    additionalInvoicing: "None",
    contactEmail: "tomas.vasiliauskas@vmetal.lt",
    whatsapp: "+370 698 77221",
    lastContactDate: "01.05.2026",
  },
  {
    lursoft: "Healthcare sector flag · cleared",
    industry: "Medical diagnostics services",
    naceCode: "86.90",
    kycForm: "Received 28.05.2025",
    idCopy: "UB + medical licence excerpt",
    meetingDate: "05.06.2025",
    clientAcceptanceComplete: "Committee 07.06.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "12.06.2025",
    additionalInvoicing: "None",
    contactEmail: "lauma.kaleja@medpark.lv",
    whatsapp: "+371 2922 6615",
    lastContactDate: "30.04.2026",
  },
  {
    lursoft: "Agri subsidy checks OK",
    industry: "Support activities for crops",
    naceCode: "01.61",
    kycForm: "Received 05.08.2025",
    idCopy: "ID + land lease summary",
    meetingDate: "14.08.2025",
    clientAcceptanceComplete: "Approved 16.08.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "22.08.2025",
    additionalInvoicing: "Milestone billing possible",
    contactEmail: "martins.celms@digifarm.lv",
    whatsapp: "+371 2833 9901",
    lastContactDate: "29.04.2026",
  },
  {
    lursoft: "Manufacturing profile verified",
    industry: "Food product manufacturing",
    naceCode: "10.89",
    kycForm: "Received 28.04.2025",
    idCopy: "ID copies + VAT cert",
    meetingDate: "06.05.2025",
    clientAcceptanceComplete: "Approved 08.05.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "15.05.2025",
    additionalInvoicing: "None",
    contactEmail: "liga.krumina@saldusfood.lv",
    whatsapp: "+371 2655 4480",
    lastContactDate: "27.04.2026",
  },
  {
    lursoft: "Norway registry verified",
    industry: "Data analytics & hosting",
    naceCode: "63.11",
    kycForm: "KYB + SOC2 letter",
    idCopy: "Passport (signatory)",
    meetingDate: "25.08.2025",
    clientAcceptanceComplete: "Approved 28.08.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "05.09.2025",
    additionalInvoicing: "Workshops quoted separately",
    contactEmail: "ingrid.solheim@fjordanalytics.no",
    whatsapp: "+47 915 44 221",
    lastContactDate: "26.04.2026",
  },
  {
    lursoft: "E-file verified · climate tech",
    industry: "Environmental consulting",
    naceCode: "70.22",
    kycForm: "Received 08.09.2025",
    idCopy: "e-Residency ID bundle",
    meetingDate: "18.09.2025",
    clientAcceptanceComplete: "Approved 20.09.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "26.09.2025",
    additionalInvoicing: "ESRS modules optional",
    contactEmail: "martin.tamm@carbonledger.ee",
    whatsapp: "+372 5344 1188",
    lastContactDate: "25.04.2026",
  },
  {
    lursoft: "Finland PRH extract OK",
    industry: "Renewable energy equipment",
    naceCode: "28.99",
    kycForm: "Received 02.10.2025",
    idCopy: "Passport + specimen",
    meetingDate: "12.10.2025",
    clientAcceptanceComplete: "Approved 15.10.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "22.10.2025",
    additionalInvoicing: "None",
    contactEmail: "olli.virtanen@helsinkicleantech.fi",
    whatsapp: "+358 40 882 1144",
    lastContactDate: "24.04.2026",
  },
  {
    lursoft: "FI regulated entity · KYB+",
    industry: "Financial service activities",
    naceCode: "64.99",
    kycForm: "Enhanced pack complete",
    idCopy: "UB + signatory IDs",
    meetingDate: "22.10.2025",
    clientAcceptanceComplete: "AML committee 28.10.2025",
    riskLevel: "Elevated (regulated)",
    contractSigned: "Yes",
    contractDate: "05.11.2025",
    additionalInvoicing: "Model updates T&M",
    contactEmail: "elin.forsberg@sfth.se",
    whatsapp: "+46 73 901 4422",
    lastContactDate: "23.04.2026",
  },
  {
    lursoft: "E-file verified · R&D grants",
    industry: "Biotechnology R&D",
    naceCode: "72.11",
    kycForm: "Received 05.11.2025",
    idCopy: "Charter + founders ID",
    meetingDate: "14.11.2025",
    clientAcceptanceComplete: "Approved 16.11.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "22.11.2025",
    additionalInvoicing: "None",
    contactEmail: "kadi.paju@tartubiotech.ee",
    whatsapp: "+372 521 8893",
    lastContactDate: "22.04.2026",
  },
  {
    lursoft: "CVR extract verified",
    industry: "Marine engineering services",
    naceCode: "33.15",
    kycForm: "Received 12.11.2025",
    idCopy: "Passport + PoA",
    meetingDate: "22.11.2025",
    clientAcceptanceComplete: "Approved 25.11.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "02.12.2025",
    additionalInvoicing: "Harbour visits actual cost",
    contactEmail: "mette.hansen@odensemaritime.dk",
    whatsapp: "+45 28 14 9033",
    lastContactDate: "21.04.2026",
  },
  {
    lursoft: "Sweden Bolagsverket OK",
    industry: "Data centre & hosting",
    naceCode: "63.11",
    kycForm: "Received 18.11.2025",
    idCopy: "ID + security posture memo",
    meetingDate: "28.11.2025",
    clientAcceptanceComplete: "Approved 30.11.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "08.12.2025",
    additionalInvoicing: "Incident response optional",
    contactEmail: "johan.ekstrom@snowpeakhosting.se",
    whatsapp: "+46 70 552 8811",
    lastContactDate: "20.04.2026",
  },
  {
    lursoft: "HRB excerpt + UBO chart",
    industry: "Legal & compliance advisory",
    naceCode: "69.10",
    kycForm: "KYB questionnaire DE",
    idCopy: "Passport (managing director)",
    meetingDate: "08.12.2025",
    clientAcceptanceComplete: "Approved 11.12.2025",
    riskLevel: "Standard",
    contractSigned: "Yes",
    contractDate: "18.12.2025",
    additionalInvoicing: "Policy drafting fixed fee",
    contactEmail: "clara.weber@baic.de",
    whatsapp: "+49 176 44199201",
    lastContactDate: "19.04.2026",
  },
  {
    lursoft: "Utility sector registry OK",
    industry: "Electric power distribution",
    naceCode: "35.13",
    kycForm: "Received 02.12.2025",
    idCopy: "ID + governance memo",
    meetingDate: "12.12.2025",
    clientAcceptanceComplete: "Approved 15.12.2025",
    riskLevel: "Elevated (regulated)",
    contractSigned: "Yes",
    contractDate: "22.12.2025",
    additionalInvoicing: "Regulatory filings extra",
    contactEmail: "darius.linge@ksgrid.lt",
    whatsapp: "+370 698 22014",
    lastContactDate: "18.04.2026",
  },
  {
    lursoft: "AIFM registry checks OK",
    industry: "Venture capital & PE funds",
    naceCode: "66.30",
    kycForm: "LP-grade DD pack",
    idCopy: "Partners IDs + fund deed excerpt",
    meetingDate: "08.12.2025",
    clientAcceptanceComplete: "IC approval 12.12.2025",
    riskLevel: "High (fund)",
    contractSigned: "Yes",
    contractDate: "18.12.2025",
    additionalInvoicing: "Capital call support T&M",
    contactEmail: "sara.lindqvist@northwind.vc",
    whatsapp: "+46 76 221 8844",
    lastContactDate: "17.04.2026",
  },
];

const portfolioShell = (
  partial: Pick<
    CustomerPortfolio,
    | "id"
    | "nr"
    | "companyName"
    | "registrationNumber"
    | "contractNo"
    | "period"
    | "scope"
    | "feeEur"
    | "emailForInvoices"
    | "clientContactName"
    | "clientContactPosition"
    | "sanctionsCheck"
    | "address"
    | "infoRequestDeadline"
    | "reportDraft"
    | "finalReport"
  > &
    Partial<Pick<CustomerPortfolio, "firstInvoiceAmountEur" | "secondInvoiceAmountEur" | "thirdInvoiceAmountEur">>,
): CustomerPortfolio => {
  const fee = partial.feeEur ?? 0;
  const q1 = Math.round(fee * 0.25);
  const q2 = Math.round(fee * 0.5);
  const q3 = fee - q1 - q2;
  const rowIdx = Math.max(
    0,
    Math.min((partial.nr ?? 1) - 1, DEMO_CUSTOMER_KYC.length - 1),
  );
  const kycRow = DEMO_CUSTOMER_KYC[rowIdx] ?? {};

  const merged: CustomerPortfolio = {
    lursoft: null,
    industry: null,
    naceCode: null,
    kycForm: null,
    idCopy: null,
    meetingDate: null,
    clientAcceptanceComplete: null,
    riskLevel: null,
    contractSigned: null,
    contractDate: null,
    additionalInvoicing: null,
    invoiceCheck: 0,
    contactEmail: null,
    whatsapp: null,
    lastContactDate: null,
    language: "English",
    framework: "Applicable statutory requirements",
    ...kycRow,
    ...partial,
    firstInvoicePercent: "25%",
    firstInvoiceAmountEur: partial.firstInvoiceAmountEur ?? q1,
    secondInvoicePercent: "50%",
    secondInvoiceAmountEur: partial.secondInvoiceAmountEur ?? q2,
    thirdInvoicePercent: "25%",
    thirdInvoiceAmountEur: partial.thirdInvoiceAmountEur ?? q3,
    sanctionsCheck:
      partial.sanctionsCheck ?? partial.companyName ?? null,
  };

  const invSum =
    (merged.firstInvoiceAmountEur ?? 0) +
    (merged.secondInvoiceAmountEur ?? 0) +
    (merged.thirdInvoiceAmountEur ?? 0);
  merged.invoiceCheck = invSum === (merged.feeEur ?? 0) ? merged.feeEur ?? 0 : 0;

  return merged;
};

export const leads: Lead[] = [
  {
    id: "l1",
    companyId: "c-baltfreight",
    primaryContactId: "cnt-l1",
    company: "Baltic Freight Co.",
    contactName: "Marta Liepa",
    email: "marta@balticfreight.lt",
    stage: "qualified",
    valueEur: 42000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-12",
  },
  {
    id: "l2",
    companyId: "c-nordicsaas",
    primaryContactId: "cnt-l2",
    company: "Nordic SaaS Labs",
    contactName: "Jonas Berg",
    email: "jonas@nordicsaas.io",
    stage: "contacted",
    valueEur: 18500,
    owner: "Laura Ozola",
    updatedAt: "2026-05-11",
  },
  {
    id: "l3",
    companyId: "c-helios",
    primaryContactId: "cnt-l3",
    company: "Helios Retail",
    contactName: "Sofia Marin",
    email: "sofia@helios.ee",
    stage: "new",
    valueEur: 67000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-10",
  },
  {
    id: "l4",
    companyId: "c-vmetal",
    primaryContactId: "cnt-l4",
    company: "Vilnius Metalworks UAB",
    contactName: "Tomas Vasiliauskas",
    email: "tomas@vmetal.lt",
    stage: "qualified",
    valueEur: 58000,
    owner: "Laura Ozola",
    updatedAt: "2026-05-13",
  },
  {
    id: "l5",
    companyId: "c-fjord",
    primaryContactId: "cnt-l5",
    company: "Fjord Analytics AS",
    contactName: "Ingrid Solheim",
    email: "ingrid@fjordanalytics.no",
    stage: "contacted",
    valueEur: 92000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-09",
  },
  {
    id: "l6",
    companyId: "cmp-liepaja-park",
    primaryContactId: "cnt-l6",
    company: "Liepaja Industrial Park",
    contactName: "Gints Ozols",
    email: "g.ozols@rpl.lv",
    stage: "new",
    valueEur: 34000,
    owner: "Miks Abols",
    updatedAt: "2026-05-08",
  },
  {
    id: "l7",
    companyId: "c-sfth",
    primaryContactId: "cnt-l7",
    company: "Stockholm Fintech Hub",
    contactName: "Elin Forsberg",
    email: "elin@sfth.se",
    stage: "qualified",
    valueEur: 127500,
    owner: "Laura Ozola",
    updatedAt: "2026-05-14",
  },
  {
    id: "l8",
    companyId: "c-medpark",
    primaryContactId: "cnt-l8",
    company: "MedPark Diagnostics",
    contactName: "Dr. Lauma Kaleja",
    email: "lauma@medpark.lv",
    stage: "contacted",
    valueEur: 41500,
    owner: "Anna Straume",
    updatedAt: "2026-05-07",
  },
  {
    id: "l9",
    companyId: "c-carbonledger",
    primaryContactId: "cnt-l9",
    company: "CarbonLedger OÜ",
    contactName: "Martin Tamm",
    email: "martin@carbonledger.ee",
    stage: "new",
    valueEur: 78000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-06",
  },
  {
    id: "l10",
    companyId: "cmp-krakow-robotics",
    primaryContactId: "cnt-l10",
    company: "Kraków Robotics SP zoo",
    contactName: "Paweł Nowicki",
    email: "p.nowicki@kr-robo.pl",
    stage: "lost",
    valueEur: 21000,
    owner: "Miks Abols",
    updatedAt: "2026-04-28",
  },
  {
    id: "l11",
    companyId: "cmp-dalku-logistics",
    primaryContactId: "cnt-l11",
    company: "Dalku Logistics SIA",
    contactName: "Renate Liepina",
    email: "renate@dalkulog.lv",
    stage: "qualified",
    valueEur: 49600,
    owner: "Laura Ozola",
    updatedAt: "2026-05-13",
  },
  {
    id: "l12",
    companyId: "c-helsinki-clean",
    primaryContactId: "cnt-l12",
    company: "Helsinki Cleantech Oy",
    contactName: "Olli Virtanen",
    email: "olli@helsinkicleantech.fi",
    stage: "contacted",
    valueEur: 103000,
    owner: "Anna Straume",
    updatedAt: "2026-05-05",
  },
  {
    id: "l13",
    companyId: "c-digifarm",
    primaryContactId: "cnt-l13",
    company: "DigiFarm Latvia",
    contactName: "Martins Celms",
    email: "martins@digifarm.lv",
    stage: "new",
    valueEur: 28900,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-04",
  },
  {
    id: "l14",
    companyId: "c-odense",
    primaryContactId: "cnt-l14",
    company: "Odense Maritime Services",
    contactName: "Mette Hansen",
    email: "mette@odensemaritime.dk",
    stage: "qualified",
    valueEur: 71500,
    owner: "Laura Ozola",
    updatedAt: "2026-05-12",
  },
  {
    id: "l15",
    companyId: "c-snowpeak",
    primaryContactId: "cnt-l15",
    company: "SnowPeak Hosting AB",
    contactName: "Johan Ekström",
    email: "johan@snowpeakhosting.se",
    stage: "contacted",
    valueEur: 54800,
    owner: "Miks Abols",
    updatedAt: "2026-05-03",
  },
  {
    id: "l16",
    companyId: "c-tartu-bio",
    primaryContactId: "cnt-l16",
    company: "Tartu Biotech LLC",
    contactName: "Kadi Paju",
    email: "kadi@tartubiotech.ee",
    stage: "new",
    valueEur: 61200,
    owner: "Anna Straume",
    updatedAt: "2026-05-02",
  },
  {
    id: "l17",
    companyId: "cmp-blacksea-grain",
    primaryContactId: "cnt-l17",
    company: "BlackSea Grain Terminal",
    contactName: "Ion Popescu",
    email: "ion@bsgrain.ro",
    stage: "lost",
    valueEur: 155000,
    owner: "Edgars Kalnins",
    updatedAt: "2026-04-15",
  },
  {
    id: "l18",
    companyId: "c-saldus",
    primaryContactId: "cnt-l18",
    company: "Saldus FoodTech",
    contactName: "Liga Krumina",
    email: "liga@saldusfood.lv",
    stage: "qualified",
    valueEur: 37200,
    owner: "Laura Ozola",
    updatedAt: "2026-05-14",
  },
  {
    id: "l19",
    companyId: "c-berlin-ai",
    primaryContactId: "cnt-l19",
    company: "Berlin AI Compliance GmbH",
    contactName: "Clara Weber",
    email: "clara@baic.de",
    stage: "contacted",
    valueEur: 88400,
    owner: "Edgars Kalnins",
    updatedAt: "2026-05-01",
  },
  {
    id: "l20",
    companyId: "cmp-liepaja-port",
    primaryContactId: "cnt-l20",
    company: "Liepaja Port Terminal",
    contactName: "Uldis Grants",
    email: "uldis@los.lv",
    stage: "new",
    valueEur: 95600,
    owner: "Miks Abols",
    updatedAt: "2026-04-30",
  },
  {
    id: "l21",
    companyId: "c-kaunas-grid",
    primaryContactId: "cnt-l21",
    company: "Kaunas Smart Grid",
    contactName: "Darius Linge",
    email: "darius@ksgrid.lt",
    stage: "qualified",
    valueEur: 63900,
    owner: "Anna Straume",
    updatedAt: "2026-05-11",
  },
  {
    id: "l22",
    companyId: "c-northwind",
    primaryContactId: "cnt-l22",
    company: "Northwind Ventures",
    contactName: "Sara Lindqvist",
    email: "sara@northwind.vc",
    stage: "contacted",
    valueEur: 222000,
    owner: "Laura Ozola",
    updatedAt: "2026-05-13",
  },
];

/** Demo rows aligned with the CLIENT PORTFOLIO sheet column layout (spreadsheet template). */
export const customers: CustomerPortfolio[] = [
  portfolioShell({
    id: "c-all-in",
    nr: 1,
    companyName: "SIA ALL IN",
    registrationNumber: 40103860926,
    contractNo: "23/8",
    period: "2022",
    scope: "Statutory financial statements audit",
    feeEur: 2200,
    emailForInvoices: "coco@loco.lv",
    clientContactName: "Janis Banis",
    clientContactPosition: "CEO",
    sanctionsCheck: 'Limited liability company "ALL IN"',
    address: "18-8 Ernesta Birznieka-Upisha St., Riga LV-1050",
    infoRequestDeadline: "04.02.2023",
    reportDraft: "06.02.2023",
    finalReport: "10.02.2023",
    firstInvoiceAmountEur: 550,
    secondInvoiceAmountEur: 1100,
    thirdInvoiceAmountEur: 550,
  }),
  portfolioShell({
    id: "c-xxx",
    nr: 2,
    companyName: "XXX SIA",
    registrationNumber: 42103077952,
    contractNo: "23/9",
    period: "2022",
    scope: "Limited assurance review of financial statements (SPUS 2400)",
    feeEur: 1600,
    emailForInvoices: "Furightback@gmail.com",
    clientContactName: "Ilze Milze",
    clientContactPosition: "CFO",
    sanctionsCheck: "XXX SIA",
    address: "12-38 Atmodas Blvd., Liepaja LV-3414",
    infoRequestDeadline: "24.02.2023",
    reportDraft: "03.03.2023",
    finalReport: "31.03.2023",
    firstInvoiceAmountEur: 400,
    secondInvoiceAmountEur: 800,
    thirdInvoiceAmountEur: 400,
  }),
  portfolioShell({
    id: "c-greenlane",
    nr: 3,
    companyName: "GreenLane Logistics SIA",
    registrationNumber: 40203344771,
    contractNo: "24/14",
    period: "2025",
    scope: "Group consolidated reporting · audit readiness",
    feeEur: 8900,
    emailForInvoices: "finance@greenlane.lv",
    clientContactName: "Kristaps Plume",
    clientContactPosition: "Finance Director",
    sanctionsCheck: "GreenLane Logistics SIA",
    address: "72 Mukusalas St., Riga LV-1004",
    infoRequestDeadline: "18.06.2025",
    reportDraft: "01.07.2025",
    finalReport: "15.07.2025",
  }),
  portfolioShell({
    id: "c-wave",
    nr: 4,
    companyName: "Wave Payments Baltic SIA",
    registrationNumber: 40103999102,
    contractNo: "25/3",
    period: "2025-2026",
    scope: "IFRS reporting support and audit preparation",
    feeEur: 12400,
    emailForInvoices: "billing@wavepayments.eu",
    clientContactName: "Annika Vitola",
    clientContactPosition: "Head of Accounting",
    sanctionsCheck: "Wave Payments Baltic SIA",
    address: "50 Skanstes St., Riga LV-1013",
    infoRequestDeadline: "22.08.2025",
    reportDraft: "05.09.2025",
    finalReport: "20.09.2025",
  }),
  portfolioShell({
    id: "c-rigatech",
    nr: 5,
    companyName: "Riga Tech Campus AS (Latvia branch)",
    registrationNumber: "LV40203988771",
    contractNo: "24/21",
    period: "2024",
    scope: "Project oversight controls testing",
    feeEur: 5600,
    emailForInvoices: "ops@rigatechcampus.lv",
    clientContactName: "Pauls Eglitis",
    clientContactPosition: "COO",
    sanctionsCheck: "Riga Tech Campus AS (Latvia branch)",
    address: "Local address pending · Riga",
    infoRequestDeadline: "12.04.2025",
    reportDraft: "22.04.2025",
    finalReport: "30.04.2025",
  }),
  portfolioShell({
    id: "c-helios",
    nr: 6,
    companyName: "Helios Retail Eesti OÜ (Latvia project)",
    registrationNumber: 48503026128,
    contractNo: "25/7",
    period: "2025",
    scope: "International group compliance assessment",
    feeEur: 7200,
    emailForInvoices: "finance@heliosretail.ee",
    clientContactName: "Sofia Marin",
    clientContactPosition: "Regional CFO",
    sanctionsCheck: "Helios Retail Eesti OÜ",
    address: "Tallinn hub · Latvia customer record",
    infoRequestDeadline: "03.05.2025",
    reportDraft: "18.05.2025",
    finalReport: "28.05.2025",
  }),
  portfolioShell({
    id: "c-baltfreight",
    nr: 7,
    companyName: "Baltic Freight Terminal SIA",
    registrationNumber: 42103111409,
    contractNo: "23/41",
    period: "2023",
    scope: "Inventory and internal controls review",
    feeEur: 3150,
    emailForInvoices: "marta@balticfreight.lt",
    clientContactName: "Marta Liepa",
    clientContactPosition: "CEO",
    sanctionsCheck: "Baltic Freight Terminal SIA",
    address: "Riga Freeport, site 12, LV-1015",
    infoRequestDeadline: "14.03.2025",
    reportDraft: "22.03.2025",
    finalReport: "05.04.2025",
  }),
  portfolioShell({
    id: "c-nordicsaas",
    nr: 8,
    companyName: "Nordic SaaS Labs AB (LV)",
    registrationNumber: "SE5566778899-LV",
    contractNo: "24/33",
    period: "2024",
    scope: "AR recognition for liabilities and revenue · SaaS",
    feeEur: 9800,
    emailForInvoices: "jonas@nordicsaas.io",
    clientContactName: "Jonas Berg",
    clientContactPosition: "Founder",
    sanctionsCheck: "Nordic SaaS Labs AB",
    address: "Remote-first · Latvia tax advisory",
    infoRequestDeadline: "08.07.2025",
    reportDraft: "20.07.2025",
    finalReport: "02.08.2025",
  }),
  portfolioShell({
    id: "c-vmetal",
    nr: 9,
    companyName: "Vilnius Metalworks Latvia branch",
    registrationNumber: 40203901234,
    contractNo: "25/11",
    period: "2025",
    scope: "Health & safety and interim controls audit preparation",
    feeEur: 4400,
    emailForInvoices: "tomas@vmetal.lt",
    clientContactName: "Tomas Vasiliauskas",
    clientContactPosition: "Plant Manager",
    sanctionsCheck: "Vilnius Metalworks UAB",
    address: "Liepaja SEZ, LV-3414",
    infoRequestDeadline: "16.09.2025",
    reportDraft: "28.09.2025",
    finalReport: "12.10.2025",
  }),
  portfolioShell({
    id: "c-medpark",
    nr: 10,
    companyName: "MedPark Diagnostics SIA",
    registrationNumber: 40103288901,
    contractNo: "24/8",
    period: "2024",
    scope: "Public procurement project accounting",
    feeEur: 5100,
    emailForInvoices: "lauma@medpark.lv",
    clientContactName: "Dr. Lauma Kaleja",
    clientContactPosition: "CEO",
    sanctionsCheck: "MedPark Diagnostics SIA",
    address: "5a Braslas St., Riga LV-1035",
    infoRequestDeadline: "01.06.2025",
    reportDraft: "14.06.2025",
    finalReport: "25.06.2025",
  }),
  portfolioShell({
    id: "c-digifarm",
    nr: 11,
    companyName: "DigiFarm Latvia SIA",
    registrationNumber: 42103290122,
    contractNo: "25/19",
    period: "2025",
    scope: "Grant accounting and subsidy reporting preparation",
    feeEur: 2750,
    emailForInvoices: "martins@digifarm.lv",
    clientContactName: "Martins Celms",
    clientContactPosition: "Managing Partner",
    sanctionsCheck: "DigiFarm Latvia SIA",
    address: "62 Valdemara St., Riga LV-1013",
    infoRequestDeadline: "11.08.2025",
    reportDraft: "22.08.2025",
    finalReport: "05.09.2025",
  }),
  portfolioShell({
    id: "c-saldus",
    nr: 12,
    companyName: "Saldus FoodTech SIA",
    registrationNumber: 42103199877,
    contractNo: "25/4",
    period: "2025",
    scope: "Manufacturing cost accounting and margin analysis",
    feeEur: 3900,
    emailForInvoices: "liga@saldusfood.lv",
    clientContactName: "Liga Krumina",
    clientContactPosition: "CFO",
    sanctionsCheck: "Saldus FoodTech SIA",
    address: "10 Zemgales St., Saldus LV-3801",
    infoRequestDeadline: "05.05.2025",
    reportDraft: "18.05.2025",
    finalReport: "30.05.2025",
  }),
  portfolioShell({
    id: "c-fjord",
    nr: 13,
    companyName: "Fjord Analytics AS",
    registrationNumber: 923456785,
    contractNo: "25/31",
    period: "2025",
    scope: "SOC 2 readiness assessment and control mapping",
    feeEur: 18200,
    emailForInvoices: "finance@fjordanalytics.no",
    clientContactName: "Ingrid Solheim",
    clientContactPosition: "COO",
    sanctionsCheck: "Fjord Analytics AS",
    address: "Fornebu Brygge 3, 1360 Fornebu, Norway",
    infoRequestDeadline: "02.09.2025",
    reportDraft: "20.09.2025",
    finalReport: "04.10.2025",
  }),
  portfolioShell({
    id: "c-carbonledger",
    nr: 14,
    companyName: "CarbonLedger OÜ",
    registrationNumber: 14576987,
    contractNo: "25/42",
    period: "2025-2026",
    scope: "ESG disclosure assurance and carbon inventory review",
    feeEur: 12450,
    emailForInvoices: "martin@carbonledger.ee",
    clientContactName: "Martin Tamm",
    clientContactPosition: "Founder",
    sanctionsCheck: "CarbonLedger OÜ",
    address: "Narva mnt 7, 10117 Tallinn, Estonia",
    infoRequestDeadline: "15.09.2025",
    reportDraft: "28.09.2025",
    finalReport: "12.10.2025",
  }),
  portfolioShell({
    id: "c-helsinki-clean",
    nr: 15,
    companyName: "Helsinki Cleantech Oy",
    registrationNumber: 2894736-2,
    contractNo: "24/55",
    period: "2024-2025",
    scope: "R&D tax credit documentation and revenue recognition review",
    feeEur: 9600,
    emailForInvoices: "olli@helsinkicleantech.fi",
    clientContactName: "Olli Virtanen",
    clientContactPosition: "CFO",
    sanctionsCheck: "Helsinki Cleantech Oy",
    address: "Vuorikatu 14 A, 00100 Helsinki, Finland",
    infoRequestDeadline: "08.10.2025",
    reportDraft: "22.10.2025",
    finalReport: "05.11.2025",
  }),
  portfolioShell({
    id: "c-sfth",
    nr: 16,
    companyName: "Stockholm Fintech Hub AB",
    registrationNumber: 5568123456,
    contractNo: "25/18",
    period: "2025",
    scope: "Regulatory reporting controls and liquidity stress testing support",
    feeEur: 28500,
    emailForInvoices: "elin@sfth.se",
    clientContactName: "Elin Forsberg",
    clientContactPosition: "Head of Risk",
    sanctionsCheck: "Stockholm Fintech Hub AB",
    address: "Birger Jarlsgatan 57, 113 56 Stockholm, Sweden",
    infoRequestDeadline: "01.11.2025",
    reportDraft: "18.11.2025",
    finalReport: "02.12.2025",
  }),
  portfolioShell({
    id: "c-tartu-bio",
    nr: 17,
    companyName: "Tartu Biotech LLC",
    registrationNumber: 10886789,
    contractNo: "25/27",
    period: "2025",
    scope: "Grant compliance audit and milestone expenditure verification",
    feeEur: 6700,
    emailForInvoices: "kadi@tartubiotech.ee",
    clientContactName: "Kadi Paju",
    clientContactPosition: "Finance Lead",
    sanctionsCheck: "Tartu Biotech LLC",
    address: "Riia 181b, 50411 Tartu, Estonia",
    infoRequestDeadline: "12.11.2025",
    reportDraft: "25.11.2025",
    finalReport: "09.12.2025",
  }),
  portfolioShell({
    id: "c-odense",
    nr: 18,
    companyName: "Odense Maritime Services ApS",
    registrationNumber: 35271841,
    contractNo: "24/63",
    period: "2024-2025",
    scope: "Dry-dock capex capitalization and lease accounting review",
    feeEur: 14300,
    emailForInvoices: "mette@odensemaritime.dk",
    clientContactName: "Mette Hansen",
    clientContactPosition: "Controller",
    sanctionsCheck: "Odense Maritime Services ApS",
    address: "Havnegade 21, 5000 Odense, Denmark",
    infoRequestDeadline: "20.11.2025",
    reportDraft: "05.12.2025",
    finalReport: "18.12.2025",
  }),
  portfolioShell({
    id: "c-snowpeak",
    nr: 19,
    companyName: "SnowPeak Hosting AB",
    registrationNumber: 5590128844,
    contractNo: "25/36",
    period: "2025-2026",
    scope: "Recurring revenue recognition and deferred revenue reconciliation",
    feeEur: 11200,
    emailForInvoices: "johan@snowpeakhosting.se",
    clientContactName: "Johan Ekstrom",
    clientContactPosition: "VP Finance",
    sanctionsCheck: "SnowPeak Hosting AB",
    address: "Master Samuelsgatan 36, 111 57 Stockholm, Sweden",
    infoRequestDeadline: "28.11.2025",
    reportDraft: "12.12.2025",
    finalReport: "20.12.2025",
  }),
  portfolioShell({
    id: "c-berlin-ai",
    nr: 20,
    companyName: "Berlin AI Compliance GmbH",
    registrationNumber: "HRB 228891 B",
    contractNo: "25/44",
    period: "2025",
    scope: "EU AI Act governance gap analysis and documentation pack",
    feeEur: 19800,
    emailForInvoices: "clara@baic.de",
    clientContactName: "Clara Weber",
    clientContactPosition: "Legal & Compliance",
    sanctionsCheck: "Berlin AI Compliance GmbH",
    address: "Rosenthaler Strasse 43, 10178 Berlin, Germany",
    infoRequestDeadline: "05.12.2025",
    reportDraft: "18.12.2025",
    finalReport: "08.01.2026",
  }),
  portfolioShell({
    id: "c-kaunas-grid",
    nr: 21,
    companyName: "Kaunas Smart Grid UAB",
    registrationNumber: 305847392,
    contractNo: "24/71",
    period: "2024-2025",
    scope: "Utility revenue accounting and regulatory tariff true-up",
    feeEur: 8800,
    emailForInvoices: "darius@ksgrid.lt",
    clientContactName: "Darius Linge",
    clientContactPosition: "CFO",
    sanctionsCheck: "Kaunas Smart Grid UAB",
    address: "Laisves al. 94, 44200 Kaunas, Lithuania",
    infoRequestDeadline: "10.12.2025",
    reportDraft: "22.12.2025",
    finalReport: "06.01.2026",
  }),
  portfolioShell({
    id: "c-northwind",
    nr: 22,
    companyName: "Northwind Ventures AB",
    registrationNumber: 5590888211,
    contractNo: "25/52",
    period: "2025-2026",
    scope: "Fund LP reporting controls and carried interest model review",
    feeEur: 45200,
    emailForInvoices: "sara@northwind.vc",
    clientContactName: "Sara Lindqvist",
    clientContactPosition: "Managing Partner",
    sanctionsCheck: "Northwind Ventures AB",
    address: "Humlegardsgatan 10, 114 46 Stockholm, Sweden",
    infoRequestDeadline: "15.12.2025",
    reportDraft: "05.01.2026",
    finalReport: "22.01.2026",
  }),
];

function companyFromPortfolio(row: CustomerPortfolio): Company {
  return {
    id: row.id,
    name: String(row.companyName ?? row.id),
    email: row.contactEmail ?? row.emailForInvoices,
    phone: row.whatsapp,
    websiteUrl: null,
    techStack: row.framework,
    tags: row.industry ? [String(row.industry)] : [],
    source: "other",
  };
}

/** Accounts referenced by leads/deals but not yet in the portfolio sheet */
const supplementalCompanies: Company[] = [
  {
    id: "cmp-liepaja-park",
    name: "Liepaja Industrial Park",
    tags: ["industrial", "latvia"],
    source: "linkedin",
    email: null,
    phone: null,
    websiteUrl: null,
    techStack: null,
  },
  {
    id: "cmp-krakow-robotics",
    name: "Kraków Robotics SP zoo",
    tags: ["manufacturing"],
    source: "cold_email",
    email: null,
    phone: null,
    websiteUrl: null,
    techStack: null,
  },
  {
    id: "cmp-dalku-logistics",
    name: "Dalku Logistics SIA",
    tags: ["logistics"],
    source: "referral",
    email: null,
    phone: null,
    websiteUrl: null,
    techStack: null,
  },
  {
    id: "cmp-blacksea-grain",
    name: "BlackSea Grain Terminal",
    tags: ["commodities"],
    source: "event",
    email: null,
    phone: null,
    websiteUrl: null,
    techStack: null,
  },
  {
    id: "cmp-liepaja-port",
    name: "Liepaja Port Terminal",
    tags: ["logistics", "port"],
    source: "website",
    email: null,
    phone: null,
    websiteUrl: null,
    techStack: null,
  },
];

export const companies: Company[] = (() => {
  const map = new Map<string, Company>();
  for (const row of customers.map(companyFromPortfolio)) {
    map.set(row.id, row);
  }
  for (const row of supplementalCompanies) {
    if (!map.has(row.id)) map.set(row.id, row);
  }
  return [...map.values()];
})();

export const contacts: Contact[] = [
  ...leads.map((l) => ({
    id: `cnt-${l.id}`,
    companyId: l.companyId,
    name: l.contactName,
    email: l.email,
    phone: null,
    role: null,
  })),
  ...customers.map((row) => ({
    id: `${row.id}-pc`,
    companyId: row.id,
    name: String(row.clientContactName ?? "Primary contact"),
    email: row.contactEmail,
    phone: row.whatsapp,
    role: row.clientContactPosition,
  })),
];

export const deals: Deal[] = [
  {
    id: "d1",
    companyId: "c-wave",
    company: "Wave Payments",
    title: "Company-wide rollout, Wave Payments",
    stage: "negotiation",
    valueEur: 84000,
    probability: 65,
    closeDate: "2026-05-28",
    owner: "Edgars Kalnins",
    serviceLine: "Audit tech",
    dealScope: "Multi-entity reporting pack",
    pricingModel: "fixed",
  },
  {
    id: "d2",
    companyId: "c-rigatech",
    company: "Riga Tech Campus",
    title: "Renewal + upsell, Riga Tech Campus",
    stage: "proposal_sent",
    valueEur: 132000,
    probability: 55,
    closeDate: "2026-06-05",
    owner: "Laura Ozola",
    serviceLine: "Controls testing",
    dealScope: "Annual oversight + automation",
    pricingModel: "hourly",
  },
  {
    id: "d3",
    companyId: "c-helios",
    company: "Helios Retail",
    title: "Pilot expansion, Helios Retail",
    stage: "discovery_call",
    valueEur: 54000,
    probability: 35,
    closeDate: "2026-06-18",
    owner: "Edgars Kalnins",
    serviceLine: "Group compliance",
    dealScope: "Latvia rollout pilot",
    pricingModel: "fixed",
  },
  {
    id: "d4",
    companyId: "c-greenlane",
    company: "GreenLane Logistics",
    title: "GreenLane, workflow automation",
    stage: "won",
    valueEur: 31000,
    probability: 100,
    closeDate: "2026-04-22",
    owner: "Laura Ozola",
    serviceLine: "Process design",
    dealScope: "Billing workflow automation",
    pricingModel: "fixed",
  },
  {
    id: "d5",
    companyId: "c-nordicsaas",
    company: "Nordic SaaS Labs",
    title: "Enterprise SOC 2 readiness, Nordic SaaS Labs",
    stage: "negotiation",
    valueEur: 97000,
    probability: 58,
    closeDate: "2026-06-02",
    owner: "Laura Ozola",
    serviceLine: "Security / compliance",
    dealScope: "SOC 2 Type II readiness",
    pricingModel: "retainer",
  },
  {
    id: "d6",
    companyId: "c-baltfreight",
    company: "Baltic Freight Co.",
    title: "Terminal automation phase 2, Baltic Freight",
    stage: "proposal_sent",
    valueEur: 61500,
    probability: 48,
    closeDate: "2026-06-12",
    owner: "Edgars Kalnins",
    serviceLine: "Automation",
    dealScope: "Terminal ops phase 2",
    pricingModel: "fixed",
  },
  {
    id: "d7",
    companyId: "c-fjord",
    company: "Fjord Analytics AS",
    title: "Fjord Analytics, embedded FP&A suite",
    stage: "lead",
    valueEur: 118000,
    probability: 32,
    closeDate: "2026-07-08",
    owner: "Anna Straume",
    serviceLine: "Analytics product",
    dealScope: "Embedded FP&A connectors",
    pricingModel: "hourly",
  },
  {
    id: "d8",
    companyId: "c-carbonledger",
    company: "CarbonLedger OÜ",
    title: "CarbonLedger, carbon audit tooling",
    stage: "proposal_sent",
    valueEur: 76500,
    probability: 52,
    closeDate: "2026-06-25",
    owner: "Edgars Kalnins",
    serviceLine: "ESG tooling",
    dealScope: "Carbon inventory audit UI",
    pricingModel: "fixed",
  },
  {
    id: "d9",
    companyId: "c-sfth",
    company: "Stockholm Fintech Hub",
    title: "Stockholm Fintech Hub, shared services MS",
    stage: "negotiation",
    valueEur: 205000,
    probability: 61,
    closeDate: "2026-05-30",
    owner: "Laura Ozola",
    serviceLine: "Risk reporting",
    dealScope: "Liquidity stress models",
    pricingModel: "retainer",
  },
  {
    id: "d10",
    companyId: "c-medpark",
    company: "MedPark Diagnostics",
    title: "MedPark, radiology capex lease structure",
    stage: "contacted",
    valueEur: 44200,
    probability: 28,
    closeDate: "2026-07-01",
    owner: "Anna Straume",
    serviceLine: "Healthcare finance",
    dealScope: "Capex lease structuring",
    pricingModel: "hourly",
  },
  {
    id: "d11",
    companyId: "c-vmetal",
    company: "Vilnius Metalworks UAB",
    title: "Vilnius Metalworks, consolidations playbook",
    stage: "proposal_sent",
    valueEur: 88900,
    probability: 44,
    closeDate: "2026-06-30",
    owner: "Miks Abols",
    serviceLine: "Manufacturing ERP",
    dealScope: "Consolidations playbook",
    pricingModel: "fixed",
  },
  {
    id: "d12",
    companyId: "c-kaunas-grid",
    company: "Kaunas Smart Grid",
    title: "Kaunas Smart Grid, regulatory filing bundle",
    stage: "discovery_call",
    valueEur: 52300,
    probability: 38,
    closeDate: "2026-07-14",
    owner: "Anna Straume",
    serviceLine: "Utility regulatory",
    dealScope: "Regulatory tariff filing bundle",
    pricingModel: "fixed",
  },
  {
    id: "d13",
    companyId: "c-odense",
    company: "Odense Maritime Services",
    title: "Odense Maritime, maintenance SaaS renewal",
    stage: "won",
    valueEur: 47800,
    probability: 100,
    closeDate: "2026-03-19",
    owner: "Laura Ozola",
    serviceLine: "SaaS renewal",
    dealScope: "Maintenance module renewal",
    pricingModel: "retainer",
  },
  {
    id: "d14",
    companyId: "c-snowpeak",
    company: "SnowPeak Hosting AB",
    title: "SnowPeak Hosting, Nordic expansion kit",
    stage: "negotiation",
    valueEur: 69200,
    probability: 63,
    closeDate: "2026-06-08",
    owner: "Miks Abols",
    serviceLine: "Hosting expansion",
    dealScope: "Nordic expansion kit",
    pricingModel: "fixed",
  },
  {
    id: "d15",
    companyId: "c-northwind",
    company: "Northwind Ventures",
    title: "Northwind Ventures, portfolio reporting mandate",
    stage: "proposal_sent",
    valueEur: 312000,
    probability: 41,
    closeDate: "2026-08-01",
    owner: "Laura Ozola",
    serviceLine: "Fund ops",
    dealScope: "Portfolio reporting mandate",
    pricingModel: "hourly",
  },
  {
    id: "d16",
    companyId: "c-berlin-ai",
    company: "Berlin AI Compliance GmbH",
    title: "Berlin AI Compliance, EU AI Act gap analysis",
    stage: "lead",
    valueEur: 93600,
    probability: 29,
    closeDate: "2026-07-22",
    owner: "Edgars Kalnins",
    serviceLine: "AI governance",
    dealScope: "EU AI Act gap analysis",
    pricingModel: "fixed",
  },
  {
    id: "d17",
    companyId: "cmp-liepaja-port",
    company: "Liepaja Port Terminal",
    title: "Liepaja Port Terminal, berth optimisation",
    stage: "proposal_sent",
    valueEur: 151000,
    probability: 47,
    closeDate: "2026-06-28",
    owner: "Miks Abols",
    serviceLine: "Port logistics",
    dealScope: "Berth optimisation sprint",
    pricingModel: "fixed",
  },
  {
    id: "d18",
    companyId: "cmp-krakow-robotics",
    company: "Kraków Robotics SP zoo",
    title: "Legacy ERP sunset, Kraków Robotics",
    stage: "lost",
    valueEur: 24000,
    probability: 0,
    closeDate: "2026-04-02",
    owner: "Miks Abols",
    serviceLine: "ERP sunset",
    dealScope: "Legacy ERP decommission",
    pricingModel: "fixed",
  },
  {
    id: "d19",
    companyId: "c-tartu-bio",
    company: "Tartu Biotech LLC",
    title: "Tartu Biotech, grant reporting automation",
    stage: "won",
    valueEur: 38900,
    probability: 100,
    closeDate: "2026-02-14",
    owner: "Anna Straume",
    serviceLine: "Grant compliance",
    dealScope: "Grant milestone automation",
    pricingModel: "fixed",
  },
  {
    id: "d20",
    companyId: "c-helsinki-clean",
    company: "Helsinki Cleantech Oy",
    title: "Helsinki Cleantech, carbon credits desk",
    stage: "negotiation",
    valueEur: 174500,
    probability: 54,
    closeDate: "2026-07-05",
    owner: "Laura Ozola",
    serviceLine: "Climate finance",
    dealScope: "Carbon credits desk build",
    pricingModel: "retainer",
  },
];

export const projects: Project[] = [
  {
    id: "p1",
    title: "Wave rollout · Wave 2 entities",
    companyId: "c-wave",
    company: "Wave Payments",
    dealId: "d1",
    scheduledStart: "2026-05-14",
    scheduledHour: 10,
    status: "active",
    owner: "Edgars Kalnins",
  },
  {
    id: "p2",
    title: "Tech campus renewal UX polish",
    companyId: "c-rigatech",
    company: "Riga Tech Campus",
    dealId: "d2",
    scheduledStart: "2026-05-14",
    scheduledHour: 14,
    status: "active",
    owner: "Laura Ozola",
  },
  {
    id: "p3",
    title: "Helios pilot checklist",
    companyId: "c-helios",
    company: "Helios Retail",
    dealId: "d3",
    scheduledStart: "2026-05-14",
    scheduledHour: null,
    status: "planned",
    owner: "Edgars Kalnins",
  },
  {
    id: "p4",
    title: "GreenLane automation QA",
    companyId: "c-greenlane",
    company: "GreenLane Logistics",
    dealId: "d4",
    scheduledStart: "2026-05-15",
    scheduledHour: 9,
    status: "done",
    owner: "Laura Ozola",
  },
  {
    id: "p5",
    title: "SOC 2 evidence locker",
    companyId: "c-nordicsaas",
    company: "Nordic SaaS Labs",
    dealId: "d5",
    scheduledStart: "2026-05-16",
    scheduledHour: 11,
    status: "active",
    owner: "Laura Ozola",
  },
  {
    id: "p6",
    title: "Baltic terminal API stubs",
    companyId: "c-baltfreight",
    company: "Baltic Freight Terminal SIA",
    dealId: "d6",
    scheduledStart: "2026-05-17",
    scheduledHour: 15,
    status: "blocked",
    owner: "Edgars Kalnins",
  },
  {
    id: "p7",
    title: "Fjord FP&A prototype",
    companyId: "c-fjord",
    company: "Fjord Analytics AS",
    dealId: "d7",
    scheduledStart: "2026-05-18",
    scheduledHour: 13,
    status: "planned",
    owner: "Anna Straume",
  },
  {
    id: "p8",
    title: "Carbon audit CSV importer",
    companyId: "c-carbonledger",
    company: "CarbonLedger OÜ",
    dealId: "d8",
    scheduledStart: "2026-05-12",
    scheduledHour: 16,
    status: "active",
    owner: "Edgars Kalnins",
  },
  {
    id: "p9",
    title: "SFTH liquidity worksheets",
    companyId: "c-sfth",
    company: "Stockholm Fintech Hub AB",
    dealId: "d9",
    scheduledStart: "2026-05-13",
    scheduledHour: 8,
    status: "active",
    owner: "Laura Ozola",
  },
  {
    id: "p10",
    title: "MedPark lease memo draft",
    companyId: "c-medpark",
    company: "MedPark Diagnostics",
    dealId: "d10",
    scheduledStart: "2026-05-11",
    scheduledHour: null,
    status: "planned",
    owner: "Anna Straume",
  },
  {
    id: "p11",
    title: "Metalworks consolidation macros",
    companyId: "c-vmetal",
    company: "Vilnius Metalworks Latvia branch",
    dealId: "d11",
    scheduledStart: "2026-06-03",
    scheduledHour: 10,
    status: "active",
    owner: "Miks Abols",
  },
  {
    id: "p12",
    title: "Kaunas tariff appendix",
    companyId: "c-kaunas-grid",
    company: "Kaunas Smart Grid UAB",
    dealId: "d12",
    scheduledStart: "2026-05-13",
    scheduledHour: 18,
    status: "active",
    owner: "Anna Straume",
  },
  {
    id: "p13",
    title: "Odense renewal packet",
    companyId: "c-odense",
    company: "Odense Maritime Services ApS",
    dealId: "d13",
    scheduledStart: "2026-05-12",
    scheduledHour: 11,
    status: "done",
    owner: "Laura Ozola",
  },
  {
    id: "p14",
    title: "SnowPeak expansion kit scoping",
    companyId: "c-snowpeak",
    company: "SnowPeak Hosting AB",
    dealId: "d14",
    scheduledStart: "2026-07-08",
    scheduledHour: 14,
    status: "planned",
    owner: "Miks Abols",
  },
  {
    id: "p15",
    title: "Northwind LP reporting wireframes",
    companyId: "c-northwind",
    company: "Northwind Ventures AB",
    dealId: "d15",
    scheduledStart: "2026-08-01",
    scheduledHour: null,
    status: "planned",
    owner: "Laura Ozola",
  },
  {
    id: "p16",
    title: "Berlin AI Act annex",
    companyId: "c-berlin-ai",
    company: "Berlin AI Compliance GmbH",
    dealId: "d16",
    scheduledStart: "2026-05-20",
    scheduledHour: 10,
    status: "active",
    owner: "Anna Straume",
  },
  {
    id: "p17",
    title: "Liepaja berth simulation MVP",
    companyId: "cmp-liepaja-port",
    company: "Liepaja Port Terminal",
    dealId: "d17",
    scheduledStart: "2026-05-28",
    scheduledHour: 15,
    status: "blocked",
    owner: "Miks Abols",
  },
  {
    id: "p18",
    title: "Kraków ERP sunset retrospective",
    companyId: "cmp-krakow-robotics",
    company: "Kraków Robotics SP zoo",
    dealId: "d18",
    scheduledStart: "2026-04-02",
    scheduledHour: null,
    status: "done",
    owner: "Miks Abols",
  },
  {
    id: "p19",
    title: "Tartu grant exporter",
    companyId: "c-tartu-bio",
    company: "Tartu Biotech LLC",
    dealId: "d19",
    scheduledStart: "2026-03-01",
    scheduledHour: 12,
    status: "done",
    owner: "Anna Straume",
  },
  {
    id: "p20",
    title: "Cleantech credits desk UI",
    companyId: "c-helsinki-clean",
    company: "Helsinki Cleantech Oy",
    dealId: "d20",
    scheduledStart: "2026-05-07",
    scheduledHour: 9,
    status: "active",
    owner: "Laura Ozola",
  },
  {
    id: "p21",
    title: "DigiFarm subsidy exporter",
    companyId: "c-digifarm",
    company: "DigiFarm Latvia SIA",
    dealId: null,
    scheduledStart: "2026-02-14",
    scheduledHour: null,
    status: "done",
    owner: "Anna Straume",
  },
  {
    id: "p22",
    title: "January onboarding sprint",
    companyId: "c-wave",
    company: "Wave Payments",
    scheduledStart: "2026-01-21",
    scheduledHour: 11,
    status: "done",
    owner: "Edgars Kalnins",
  },
  {
    id: "p23",
    title: "Q4 roadmap freeze",
    companyId: "c-northwind",
    company: "Northwind Ventures AB",
    scheduledStart: "2026-11-30",
    scheduledHour: 17,
    status: "planned",
    owner: "Laura Ozola",
  },
];

export const invoices: Invoice[] = [
  {
    id: "inv-1",
    dealId: "d4",
    companyId: "c-greenlane",
    amountEur: 8900,
    status: "paid",
    paymentMethod: "SEPA",
    note: "Annual advisory · installment 2/3",
    updatedAt: "2026-05-01",
  },
  {
    id: "inv-2",
    dealId: "d1",
    companyId: "c-wave",
    amountEur: 42000,
    status: "sent",
    paymentMethod: null,
    note: "Rollout milestone 1",
    updatedAt: "2026-05-12",
  },
  {
    id: "inv-3",
    dealId: null,
    companyId: "c-fjord",
    amountEur: 9200,
    status: "draft",
    paymentMethod: null,
    note: "SOC readiness discovery",
    updatedAt: "2026-05-13",
  },
  {
    id: "inv-4",
    dealId: "d13",
    companyId: "c-odense",
    amountEur: 14300,
    status: "paid",
    paymentMethod: "Card",
    note: "Renewal FY26",
    updatedAt: "2026-03-20",
  },
];

export const activityNotes: ActivityNote[] = [
  {
    id: "act-1",
    parentKind: "deal",
    parentId: "d1",
    kind: "call",
    title: "CFO alignment",
    body: "Confirmed timeline for staged rollout; legal wants revised DPA by Friday.",
    occurredAt: "2026-05-11T14:30:00",
  },
  {
    id: "act-2",
    parentKind: "deal",
    parentId: "d9",
    kind: "email",
    title: "Workshop agenda",
    body: "Sent draft agenda + attendee list for liquidity workshop.",
    occurredAt: "2026-05-10T09:15:00",
  },
  {
    id: "act-3",
    parentKind: "company",
    parentId: "c-northwind",
    kind: "meeting",
    title: "IC preview",
    body: "Walked through reporting deliverables; partner wants hourly cap clarified.",
    occurredAt: "2026-05-09T16:00:00",
  },
  {
    id: "act-4",
    parentKind: "lead",
    parentId: "l7",
    kind: "note",
    title: "Warm intro",
    body: "Referral via portfolio CFO · budget confirmed H2.",
    occurredAt: "2026-05-08T11:00:00",
  },
];

export const goals: Goal[] = [
  {
    id: "goal-st-1",
    horizon: "short_term",
    longTermGoalId: "goal-lt-1",
    visionParentGoalId: null,
    title: "Wave Payments · Wave 2 scope signed",
    metric: "Signed SOW + staged milestones doc with CFO",
    targetDate: "2026-06-30",
    progress: 62,
    status: "active",
    area: "money",
    reviewNote: "Legal reviewing indemnity clause · ping Fri",
    sortOrder: 0,
    updatedAt: "2026-05-13",
  },
  {
    id: "goal-st-2",
    horizon: "short_term",
    longTermGoalId: "goal-lt-2",
    visionParentGoalId: null,
    title: "SOC 2 evidence locker MVP in prod",
    metric: "10 pilot orgs uploading docs; audit trail export works",
    targetDate: "2026-07-15",
    progress: 38,
    status: "active",
    area: "work",
    reviewNote: "CSV import edge cases still flaky",
    sortOrder: 1,
    updatedAt: "2026-05-12",
  },
  {
    id: "goal-st-3",
    horizon: "short_term",
    longTermGoalId: "goal-lt-3",
    visionParentGoalId: null,
    title: "Referral outreach · 12 warm intros",
    metric: "12 conversations logged with source + next step",
    targetDate: "2026-06-01",
    progress: 75,
    status: "active",
    area: "relationships",
    reviewNote: "7 done · 5 scheduled",
    sortOrder: 2,
    updatedAt: "2026-05-11",
  },
  {
    id: "goal-lt-1",
    horizon: "long_term",
    longTermGoalId: null,
    visionParentGoalId: null,
    title: "Weighted pipeline ≥ €420k run rate",
    metric: "Rolling 90d weighted value; 4+ discovery calls / month",
    targetDate: "2026-12-31",
    progress: 48,
    status: "active",
    area: "money",
    reviewNote: "Q3 review: tighten ICP on fintech compliance",
    sortOrder: 0,
    updatedAt: "2026-05-10",
  },
  {
    id: "goal-lt-2",
    horizon: "long_term",
    longTermGoalId: null,
    visionParentGoalId: null,
    title: "Productize “advisory sprint” playbook",
    metric: "Template + pricing + 3 paid repeats without custom SOW",
    targetDate: "2026-09-30",
    progress: 22,
    status: "active",
    area: "work",
    reviewNote: "Draft notion structure - need case study",
    sortOrder: 1,
    updatedAt: "2026-05-09",
  },
  {
    id: "goal-lt-3",
    horizon: "long_term",
    longTermGoalId: null,
    visionParentGoalId: null,
    title: "Associate hire + delegation map",
    metric: "One 0.5 FTE contractor; 5 recurring tasks off your plate",
    targetDate: "2026-11-15",
    progress: 15,
    status: "active",
    area: "self",
    reviewNote: "JD drafted; budget sign-off pending",
    sortOrder: 2,
    updatedAt: "2026-05-08",
  },
  {
    id: "goal-lt-4",
    horizon: "long_term",
    longTermGoalId: null,
    visionParentGoalId: null,
    title: "Sustainability · training load you can keep",
    metric: "2 structured runs/week + sleep log 5/7 nights",
    targetDate: "2026-12-31",
    progress: 55,
    status: "active",
    area: "body",
    reviewNote: "Travel weeks exception rule documented",
    sortOrder: 3,
    updatedAt: "2026-05-07",
  },
];
